"""
Argus FastAPI backend.

This is a thin HTTP layer over the exact same `argus` package used by the
MCP server (`argus/server.py`) and the CLI (`demo.py`). No triage logic
lives here — this file only does routing, request/response shaping, and
holding the human-approval state for a running session. That way the
MCP server, the CLI, and this API can never disagree about what Argus
actually decided, because they all call the same functions underneath.

Run it (from the repo root):
    pip install -r backend/requirements.txt
    uvicorn backend.main:app --reload --port 8000

Then open http://127.0.0.1:8000/docs for an interactive API explorer
(auto-generated by FastAPI — nothing extra to build for that).
"""

from __future__ import annotations

import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from fastapi import FastAPI, HTTPException  # noqa: E402
from fastapi.middleware.cors import CORSMiddleware  # noqa: E402
from pydantic import BaseModel  # noqa: E402

from argus import correlation, data_store, rca_engine, remediation  # noqa: E402
from eval.backtest import run_backtest  # noqa: E402

app = FastAPI(
    title="Argus AI SRE Backend",
    description=(
        "REST API over the Argus incident-triage pipeline: correlate signals, "
        "propose a root-cause hypothesis, propose a risk-gated remediation, "
        "and let a human approve anything above low risk."
    ),
    version="0.1.0",
)

# Wide-open CORS is fine here: this is a portfolio project with no real
# user data or credentials behind it. Do NOT ship this as-is for a real
# deployment — lock allow_origins down to your actual frontend's URL.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# In-memory decision store: incident_id -> full trace + approval state.
# Resets every time the server restarts. That's the right tradeoff for a
# demo; a real deployment would persist this in a database so an
# approval isn't lost if the process restarts mid-incident.
_decisions: dict[str, dict[str, Any]] = {}


class ApproveRequest(BaseModel):
    approved_by: str = "unknown"


def _get_or_create_trace(incident_id: str) -> dict[str, Any]:
    if incident_id in _decisions:
        return _decisions[incident_id]

    try:
        context = correlation.build_incident_context(incident_id)
    except KeyError:
        raise HTTPException(status_code=404, detail=f"Unknown incident: {incident_id}")

    rca = rca_engine.propose_rca(context)
    plan = remediation.propose_remediation(context, rca)
    execution = remediation.execute_remediation(plan, approved=False)

    record = {
        "incident_id": incident_id,
        "context": context,
        "rca": rca,
        "remediation": plan,
        "execution": execution,
        "approved_by": None,
        "approved_at": None,
    }
    _decisions[incident_id] = record
    return record


@app.get("/")
def root() -> dict[str, str]:
    """Health check / landing info."""
    return {"service": "argus-backend", "status": "ok", "docs": "/docs"}


@app.get("/incidents")
def list_incidents() -> list[dict[str, Any]]:
    """List every incident Argus currently knows about (still the 15
    synthetic incidents until data_store.py is pointed at something real)."""
    return data_store.list_active_alerts()


@app.get("/incidents/{incident_id}/trace")
def get_trace(incident_id: str) -> dict[str, Any]:
    """Get (or compute, on first call) the full triage trace for one
    incident: correlated context, RCA hypothesis, proposed remediation,
    and current execution/approval status."""
    return _get_or_create_trace(incident_id)


@app.post("/incidents/{incident_id}/approve")
def approve(incident_id: str, body: ApproveRequest) -> dict[str, Any]:
    """A human approves a remediation that was escalated (medium/high
    risk). No-op if the incident's action was already executed, was
    already a no-op, or hasn't been escalated yet."""
    record = _get_or_create_trace(incident_id)

    if record["execution"]["status"] != "escalated_for_human_approval":
        return record

    execution = remediation.execute_remediation(record["remediation"], approved=True)
    record["execution"] = execution
    record["approved_by"] = body.approved_by
    record["approved_at"] = datetime.now(timezone.utc).isoformat()
    return record


@app.post("/incidents/{incident_id}/reset")
def reset(incident_id: str) -> dict[str, str]:
    """Clear a stored decision so the incident can be triaged again from
    scratch. Useful for demos and for re-running tests."""
    _decisions.pop(incident_id, None)
    return {"status": "reset", "incident_id": incident_id}


@app.get("/backtest")
def backtest() -> dict[str, Any]:
    """Run the same backtest as `python demo.py` / `eval/backtest.py` and
    return just the summary metrics as JSON."""
    result = run_backtest(verbose=False)
    return result["summary"]
